---
abstract: 'Powerful, extensible charting.'
author:
  - 'Cory ''G' Watson <gphat@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Chart-Clicker
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0.4302
  DateTime::Set: 0.25
  Geometry::Primitive: 0.13
  Graphics::Primitive: 0.38
  Graphics::Primitive::Driver::Cairo: 0.33
  IO::File: 0
  Layout::Manager: 0.2
  Math::Trig: 1.18
  Moose: 0.57
  MooseX::AttributeHelpers: 0.13
  Scalar::Util: 1.19
version: 2.18
