---
abstract: 'Powerful, extensible charting.'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.86'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Chart-Clicker
no_index:
  directory:
    - example
    - inc
    - t
requires:
  Color::Scheme: 1.02
  DateTime: 0.47
  DateTime::Set: 0.27
  Geometry::Primitive: 0.13
  Graphics::Color: 0.2
  Graphics::Primitive: 0.41
  Graphics::Primitive::Driver::Cairo: 0.37
  IO::File: 0
  Layout::Manager: 0.2
  Math::Complex: 1.56
  Moose: 0.76
  MooseX::AttributeHelpers: 0.17
  Scalar::Util: 1.19
resources:
  license: http://dev.perl.org/licenses/
version: 2.31
