---
abstract: 'Powerful, extensible charting.'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Chart-Clicker
no_index:
  directory:
    - example
    - inc
    - t
recommends:
  Statistics::Basic: 0
requires:
  Color::Scheme: 1.02
  DateTime: 0.47
  DateTime::Set: 0.27
  Geometry::Primitive: 0.22
  Graphics::Color: 0.27
  Graphics::Primitive: 0.49
  Graphics::Primitive::Driver::Cairo: 0.42
  IO::File: 0
  Layout::Manager: 0.31
  List::Util: 0
  Math::Complex: 1.56
  Math::Gradient: 0.04
  Moose: 0.76
  Scalar::Util: 1.19
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/gphat/chart-clicker
version: 2.68
